OperationOutcome as Error if returned by the FHIR service
SanteonNL/go-fhir-client pull request #2
Opened 2024-09-09 12:58 UTC by tader

[INT-255: Parse OperationOutcome on the client side](https://linear.app/zorg-bij-jou/issue/INT-255/orca-or-return-operationoutcome-on-error-and-parse-them-client-side)

2024-09-10 07:58 UTC, dwelman commented on client.go
> +		// Checking for OperationOutcome
Nitpick: This comment doesn't add any information not provided by the method name in the next line

2024-09-10 07:59 UTC, dwelman approved these changes
Approved, just minor nitpick about comments

2024-09-10 11:19 UTC, reinkrul requested changes

2024-09-10 11:19 UTC, reinkrul commented on client.go
> +	if err = checkForOperationOutcome(data); err != nil {
> Operation outcomes returned SHOULD be in alignment with the HTTP response code. For example, if the HTTP code indicates a failure (300+), at least one of the issues should have a severity of "error", indicating the reason for the failure.
(https://www.hl7.org/fhir/r4b/operationoutcome.html#using)

and

> Operation outcomes are sets of error, warning and information messages that provide detailed information about the outcome of an attempted system operation. They are provided as a direct system response, or component of one, and provide information about the outcome of the operation.

(note "informational")

In other words, an operation outcome for an OK status could be considered as the opertion succeeded? I think the response the FHIR server returns when creating a Bundle (FHIR transaction) also contains an OperationOutcome.

2024-09-10 11:19 UTC, reinkrul commented on operation_outcome.go
> +		if issue.Diagnostics != nil {
diagnostics being an optional field (and details as well), don't we always want an entry for the particular operationoutcome? Even when diagnostics is not set? (and maybe support detail field as well). Or add a note/TODO that we currently don't support it ehre?

2024-09-13 12:41 UTC, tader commented
Hey @reinkrul I have made changes to the PR, I hope I correctly understood you remarks 😉

2024-09-13 13:13 UTC, merged